package identity

// Adjective + noun wordlists for the deterministic device-name generator.
// Keep these PG-safe, easy to pronounce, and recognisable across the major
// languages our docs target. Aim for several hundred entries in each list:
// the product space drives how many devices can share a LAN before
// birthday-paradox collisions become noticeable (≥50% chance once the
// number of robots approaches √(adj × noun)).

var adjectives = []string{
	"agile", "amber", "ancient", "arctic", "ashen", "astral", "auburn", "azure",
	"balmy", "bashful", "blazing", "blissful", "bold", "boreal", "brave", "breezy",
	"bright", "bronze", "brisk", "buoyant", "burly", "calm", "candid", "carbon",
	"caustic", "celestial", "cerulean", "chestnut", "chipper", "chrome", "civic", "classic",
	"clever", "cobalt", "coastal", "comet", "copper", "coral", "cordial", "cosmic",
	"crested", "crimson", "crisp", "crystal", "curious", "dapper", "dawn", "dazzling",
	"deep", "demure", "diligent", "distant", "dreamy", "dusky", "dusty", "eager",
	"earnest", "easy", "elated", "electric", "elegant", "ember", "emerald", "endless",
	"epic", "etched", "ethereal", "exact", "fabled", "fair", "famous", "fancy",
	"fearless", "feline", "fern", "fierce", "fiery", "first", "fleet", "fluent",
	"flying", "foggy", "forest", "fragrant", "frank", "frosty", "gallant", "gentle",
	"gilded", "glacial", "gleaming", "glowing", "golden", "graceful", "grand", "granite",
	"green", "happy", "hardy", "harmonic", "hazel", "heroic", "hidden", "holy",
	"honest", "humble", "icy", "indigo", "inland", "inner", "intrepid", "iron",
	"ivory", "jade", "jolly", "jovial", "joyful", "jubilant", "keen", "kind",
	"lagoon", "lavender", "lazy", "leafy", "lemon", "level", "lilac", "limber",
	"lively", "lone", "lucid", "lucky", "lunar", "lustrous", "maple", "marine",
	"meadow", "merry", "mighty", "mild", "minty", "misty", "modest", "moonlit",
	"mossy", "mountain", "muted", "mystic", "navy", "nebula", "neon", "nimble",
	"noble", "nordic", "nutty", "oasis", "ocean", "olive", "onyx", "open",
	"orchid", "outer", "pacific", "pale", "patient", "peaceful", "pearl", "peppy",
	"piney", "placid", "playful", "pluvial", "polar", "polished", "potent", "prairie",
	"primal", "prudent", "pure", "quaint", "quartz", "quick", "quiet", "radiant",
	"raindrop", "raven", "ready", "regal", "remote", "river", "rosy", "rugged",
	"rural", "russet", "rustic", "saffron", "salty", "sandy", "sapphire", "savvy",
	"scarlet", "secret", "serene", "shadow", "shady", "sharp", "shimmer", "shore",
	"silent", "silver", "simple", "sleek", "snowy", "solar", "solid", "sonic",
	"spirited", "splendid", "spry", "stark", "starry", "stately", "stoic", "stony",
	"storm", "subtle", "summer", "sunlit", "sunny", "sunset", "swift", "tangerine",
	"tawny", "teal", "tender", "thoughtful", "thrifty", "tidal", "timber", "tiny",
	"tranquil", "tropic", "trusty", "tundra", "twilight", "umber", "upbeat", "urban",
	"vagrant", "valiant", "vast", "velvet", "verdant", "vermilion", "vibrant", "violet",
	"vivid", "warm", "watchful", "wavy", "weathered", "wild", "wily", "windy",
	"winsome", "wintry", "wise", "wonder", "woodland", "yearling", "young", "zealous",
}

var nouns = []string{
	"acorn", "albatross", "alder", "alpaca", "anchor", "antler", "apricot", "arrow",
	"ash", "aspen", "azalea", "badger", "bamboo", "banyan", "barnacle", "basalt",
	"basin", "bay", "beacon", "beaver", "beech", "beetle", "berry", "bison",
	"bitterroot", "bobcat", "bough", "boulder", "branch", "breaker", "breeze", "briar",
	"brook", "bryony", "burrow", "butte", "buttress", "cactus", "caldera", "calla",
	"camellia", "canary", "canyon", "cape", "cardinal", "caribou", "cascade", "cedar",
	"chamois", "channel", "chinook", "cliff", "clover", "cobble", "comet", "compass",
	"cone", "conifer", "coral", "cottage", "cougar", "creek", "crescent", "cricket",
	"crocus", "crow", "current", "cypress", "daffodil", "daisy", "dale", "dawn",
	"daybreak", "deer", "delta", "den", "dewdrop", "dolphin", "dove", "dragonfly",
	"dune", "eagle", "eddy", "elk", "ember", "estuary", "fawn", "feather",
	"fennel", "fern", "field", "finch", "fjord", "flax", "flora", "foal",
	"fog", "footpath", "forest", "fox", "frost", "galleon", "garnet", "geode",
	"geyser", "gladewing", "glen", "goose", "gosling", "granite", "grove", "gull",
	"hare", "harvest", "hawk", "haze", "hazel", "heath", "hedge", "heron",
	"hibiscus", "hillside", "hollow", "holly", "horizon", "hummingbird", "icicle", "iguana",
	"iris", "ivy", "jackal", "jasmine", "jay", "juniper", "kestrel", "kettle",
	"kitten", "kookaburra", "lagoon", "lantern", "larch", "lark", "lattice", "leaf",
	"ledge", "lemur", "leopard", "lichen", "lily", "linden", "lion", "lobster",
	"loon", "lupine", "lynx", "magpie", "mango", "maple", "marble", "marsh",
	"meadow", "merlin", "mesa", "midnight", "mink", "mist", "moat", "moonbeam",
	"moor", "moss", "mosswood", "mountain", "murmur", "nautilus", "nectar", "nettle",
	"newt", "nightjar", "nimbus", "north", "nova", "oak", "oasis", "ocean",
	"olive", "onyx", "opal", "orca", "orchard", "orchid", "osprey", "otter",
	"pansy", "panther", "papaya", "parsley", "pasture", "patch", "peach", "pebble",
	"penguin", "petal", "phoenix", "pillar", "pine", "pioneer", "plover", "plume",
	"pond", "poppy", "prairie", "primrose", "puffin", "quail", "quartz", "quill",
	"quince", "rabbit", "raccoon", "rapids", "raven", "redwood", "reed", "ridge",
	"rill", "ripple", "river", "robin", "rook", "rose", "rosemary", "rowan",
	"sable", "sage", "salmon", "sapling", "satellite", "saturn", "savanna", "scarab",
	"sea", "seagull", "seal", "shadow", "shale", "shore", "shrike", "siskin",
	"sky", "slate", "snail", "snowdrop", "songbird", "sparrow", "spire", "spruce",
	"squirrel", "starling", "steppe", "stoat", "stone", "stream", "summit", "swan",
}
